name: Deploy Branch to GitHub Pages

on:
  push:
    branches-ignore:
      - main
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages  # Always push to the gh-pages branch
          folder: .asv/html  # The folder your site is built to
          target-folder: ${{ github.ref_name }}  # Deploy into a folder named after the branch
          clean: false  # Important: Prevents cleaning of existing files in the branch